### ISSUE TITLE
Proposal: add [version] to BEMHTML

### ISSUE THREAD

**Issue by Yeti-or** [enb/enb-bemxjst#198]
In `dev` build add `version` prop to BEMHTML instance, with version of `bem-xjst` we build on.

**Comment by blond** [comment]
In `bem-xjst@4+` has no `dev` mode.

We can add option (for example `provideVersion: true`) and use it in ENB `development` mode.

**Comment by miripiruni** [comment]
@Yeti-or can you provide usecase for `version` prop?

**Comment by zxqfox** [comment]
@miripiruni The same as `process.version`

**Comment by zxqfox** [comment]
@blond Are you sure we should extend BEMHTML instance in dev mode? It's ok for me but also it's strange to hear that from you. 😸

**Comment by miripiruni** [comment]
@zxqfox can you describe more?

**Comment by zxqfox** [comment]
@miripiruni Describe what?) How it's useful to see a version from the repl?

**Comment by miripiruni** [comment]
@zxqfox Okay. The only question is: you accidentally do not intend to use it as a "feature detection"?

**Comment by zxqfox** [comment]
@miripiruni Well, sure not. But it's useful for debugging and informational purposes.
Anyway I'm against adding this to production build.

**Comment by miripiruni** [comment]
@zxqfox 👍

**Comment by blond** [comment]
> Are you sure we should extend BEMHTML instance in dev mode? It's ok for me but also it's strange to hear that from you. 😸

@zxqfox I think every man able to decide where to use option.

**Comment by zxqfox** [comment]
> I think every man able to decide where to use option.

Liberty is the new freedom, lol.

**Comment by miripiruni** [comment]
Any normal developer can do `require('bem-xsjt/package.json').version` or `npm ls | grep bem-xjst`.

We don’t need `version` field and moreover option (`provideVersion: true`) for this. It’s useless and weird.
