### ISSUE TITLE
Not possible disable sourcemap

### ISSUE THREAD

**Issue by baymer** [enb/enb-bemxjst#289]
Because here https://github.com/enb/enb-bemxjst/blob/master/techs/bem-xjst.js#L142 not checks is the `sourcemap` enable or not (https://github.com/enb/enb-bemxjst/blob/master/techs/bem-xjst.js#L110).

**Comment by baymer** [comment]
I think fix is
```javascript
if (this._sourcemap) {
  engineOptions.sourceMap = { from: this._target };
}```

**Comment by tadatuta** [comment]
@baymer, implemented just the way you suggested but with inverted condition to keep the change backward compatible.

**Comment by tadatuta** [comment]
+ enb-bemxjst@8.10.6
